var wms_layers = [];


        var lyr_GoogleSatellite_0 = new ol.layer.Tile({
            'title': 'Google Satellite',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}'
            })
        });
var format_GHWS_1 = new ol.format.GeoJSON();
var features_GHWS_1 = format_GHWS_1.readFeatures(json_GHWS_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_GHWS_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_GHWS_1.addFeatures(features_GHWS_1);
var lyr_GHWS_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_GHWS_1, 
                style: style_GHWS_1,
                popuplayertitle: 'GHWS',
                interactive: true,
    title: 'GHWS<br />\
    <img src="styles/legend/GHWS_1_0.png" /> 1<br />' });
var format_vip_inclusive_2 = new ol.format.GeoJSON();
var features_vip_inclusive_2 = format_vip_inclusive_2.readFeatures(json_vip_inclusive_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_vip_inclusive_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_vip_inclusive_2.addFeatures(features_vip_inclusive_2);
var lyr_vip_inclusive_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_vip_inclusive_2, 
                style: style_vip_inclusive_2,
                popuplayertitle: 'vip_inclusive',
                interactive: true,
    title: 'vip_inclusive<br />\
    <img src="styles/legend/vip_inclusive_2_0.png" /> 2<br />\
    <img src="styles/legend/vip_inclusive_2_1.png" /> 4<br />' });
var format_Doubleoffsettwinpittoilet_3 = new ol.format.GeoJSON();
var features_Doubleoffsettwinpittoilet_3 = format_Doubleoffsettwinpittoilet_3.readFeatures(json_Doubleoffsettwinpittoilet_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Doubleoffsettwinpittoilet_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Doubleoffsettwinpittoilet_3.addFeatures(features_Doubleoffsettwinpittoilet_3);
var lyr_Doubleoffsettwinpittoilet_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Doubleoffsettwinpittoilet_3, 
                style: style_Doubleoffsettwinpittoilet_3,
                popuplayertitle: 'Double offset twin pit toilet',
                interactive: true,
    title: 'Double offset twin pit toilet<br />\
    <img src="styles/legend/Doubleoffsettwinpittoilet_3_0.png" /> 2<br />\
    <img src="styles/legend/Doubleoffsettwinpittoilet_3_1.png" /> 4<br />\
    <img src="styles/legend/Doubleoffsettwinpittoilet_3_2.png" /> 5<br />' });
var format_rwc_12m_no_tank_4 = new ol.format.GeoJSON();
var features_rwc_12m_no_tank_4 = format_rwc_12m_no_tank_4.readFeatures(json_rwc_12m_no_tank_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_rwc_12m_no_tank_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_rwc_12m_no_tank_4.addFeatures(features_rwc_12m_no_tank_4);
var lyr_rwc_12m_no_tank_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_rwc_12m_no_tank_4, 
                style: style_rwc_12m_no_tank_4,
                popuplayertitle: 'rwc_12m_no_tank',
                interactive: true,
    title: 'rwc_12m_no_tank<br />\
    <img src="styles/legend/rwc_12m_no_tank_4_0.png" /> 1<br />\
    <img src="styles/legend/rwc_12m_no_tank_4_1.png" /> 2<br />' });
var format_rwc_12m_w_6kl_tank_5 = new ol.format.GeoJSON();
var features_rwc_12m_w_6kl_tank_5 = format_rwc_12m_w_6kl_tank_5.readFeatures(json_rwc_12m_w_6kl_tank_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_rwc_12m_w_6kl_tank_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_rwc_12m_w_6kl_tank_5.addFeatures(features_rwc_12m_w_6kl_tank_5);
var lyr_rwc_12m_w_6kl_tank_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_rwc_12m_w_6kl_tank_5, 
                style: style_rwc_12m_w_6kl_tank_5,
                popuplayertitle: 'rwc_12m_w_6kl_tank',
                interactive: true,
                title: '<img src="styles/legend/rwc_12m_w_6kl_tank_5.png" /> rwc_12m_w_6kl_tank'
            });
var format_DeliveryShipWSanto_6 = new ol.format.GeoJSON();
var features_DeliveryShipWSanto_6 = format_DeliveryShipWSanto_6.readFeatures(json_DeliveryShipWSanto_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryShipWSanto_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryShipWSanto_6.addFeatures(features_DeliveryShipWSanto_6);
var lyr_DeliveryShipWSanto_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryShipWSanto_6, 
                style: style_DeliveryShipWSanto_6,
                popuplayertitle: 'Delivery – Ship W. Santo',
                interactive: true,
                title: '<img src="styles/legend/DeliveryShipWSanto_6.png" /> Delivery – Ship W. Santo'
            });
var format_DeliveryShiptoTasarikiLandTransport_7 = new ol.format.GeoJSON();
var features_DeliveryShiptoTasarikiLandTransport_7 = format_DeliveryShiptoTasarikiLandTransport_7.readFeatures(json_DeliveryShiptoTasarikiLandTransport_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryShiptoTasarikiLandTransport_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryShiptoTasarikiLandTransport_7.addFeatures(features_DeliveryShiptoTasarikiLandTransport_7);
var lyr_DeliveryShiptoTasarikiLandTransport_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryShiptoTasarikiLandTransport_7, 
                style: style_DeliveryShiptoTasarikiLandTransport_7,
                popuplayertitle: 'Delivery – Ship to Tasariki/Land Transport',
                interactive: true,
                title: '<img src="styles/legend/DeliveryShiptoTasarikiLandTransport_7.png" /> Delivery – Ship to Tasariki/Land Transport'
            });
var format_delivery__ship_to_tasarikiland_transport_8 = new ol.format.GeoJSON();
var features_delivery__ship_to_tasarikiland_transport_8 = format_delivery__ship_to_tasarikiland_transport_8.readFeatures(json_delivery__ship_to_tasarikiland_transport_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_delivery__ship_to_tasarikiland_transport_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_delivery__ship_to_tasarikiland_transport_8.addFeatures(features_delivery__ship_to_tasarikiland_transport_8);
var lyr_delivery__ship_to_tasarikiland_transport_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_delivery__ship_to_tasarikiland_transport_8, 
                style: style_delivery__ship_to_tasarikiland_transport_8,
                popuplayertitle: 'delivery__ship_to_tasarikiland_transport',
                interactive: true,
                title: '<img src="styles/legend/delivery__ship_to_tasarikiland_transport_8.png" /> delivery__ship_to_tasarikiland_transport'
            });
var format_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9 = new ol.format.GeoJSON();
var features_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9 = format_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.readFeatures(json_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.addFeatures(features_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9);
var lyr_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9, 
                style: style_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9,
                popuplayertitle: 'Delivery – Ship to Araki or Land Transport to Landing site and then by Boat',
                interactive: true,
                title: '<img src="styles/legend/DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.png" /> Delivery – Ship to Araki or Land Transport to Landing site and then by Boat'
            });
var format_DeliveryByBoat_10 = new ol.format.GeoJSON();
var features_DeliveryByBoat_10 = format_DeliveryByBoat_10.readFeatures(json_DeliveryByBoat_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryByBoat_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryByBoat_10.addFeatures(features_DeliveryByBoat_10);
var lyr_DeliveryByBoat_10 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryByBoat_10, 
                style: style_DeliveryByBoat_10,
                popuplayertitle: 'Delivery – By Boat',
                interactive: true,
                title: '<img src="styles/legend/DeliveryByBoat_10.png" /> Delivery – By Boat'
            });
var format_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11 = new ol.format.GeoJSON();
var features_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11 = format_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.readFeatures(json_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.addFeatures(features_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11);
var lyr_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11, 
                style: style_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11,
                popuplayertitle: 'Delivery – Land Transport to Landing site, then by Boat to school',
                interactive: true,
                title: '<img src="styles/legend/DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.png" /> Delivery – Land Transport to Landing site, then by Boat to school'
            });
var format_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12 = new ol.format.GeoJSON();
var features_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12 = format_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.readFeatures(json_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.addFeatures(features_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12);
var lyr_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12, 
                style: style_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12,
                popuplayertitle: 'Delivery – Ship to Malo - Nanuku then Land Transport to Individual Schools',
                interactive: true,
                title: '<img src="styles/legend/DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.png" /> Delivery – Ship to Malo - Nanuku then Land Transport to Individual Schools'
            });
var format_DeliveryShipBBcoast_13 = new ol.format.GeoJSON();
var features_DeliveryShipBBcoast_13 = format_DeliveryShipBBcoast_13.readFeatures(json_DeliveryShipBBcoast_13, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryShipBBcoast_13 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryShipBBcoast_13.addFeatures(features_DeliveryShipBBcoast_13);
var lyr_DeliveryShipBBcoast_13 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryShipBBcoast_13, 
                style: style_DeliveryShipBBcoast_13,
                popuplayertitle: 'Delivery – Ship BB coast',
                interactive: true,
                title: '<img src="styles/legend/DeliveryShipBBcoast_13.png" /> Delivery – Ship BB coast'
            });
var format_DeliveryLandTransport_14 = new ol.format.GeoJSON();
var features_DeliveryLandTransport_14 = format_DeliveryLandTransport_14.readFeatures(json_DeliveryLandTransport_14, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_DeliveryLandTransport_14 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_DeliveryLandTransport_14.addFeatures(features_DeliveryLandTransport_14);
var lyr_DeliveryLandTransport_14 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_DeliveryLandTransport_14, 
                style: style_DeliveryLandTransport_14,
                popuplayertitle: 'Delivery – Land Transport',
                interactive: true,
                title: '<img src="styles/legend/DeliveryLandTransport_14.png" /> Delivery – Land Transport'
            });
var format_support_phase3_15 = new ol.format.GeoJSON();
var features_support_phase3_15 = format_support_phase3_15.readFeatures(json_support_phase3_15, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_support_phase3_15 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_support_phase3_15.addFeatures(features_support_phase3_15);
var lyr_support_phase3_15 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_support_phase3_15, 
                style: style_support_phase3_15,
                popuplayertitle: 'support_phase 3',
                interactive: true,
                title: '<img src="styles/legend/support_phase3_15.png" /> support_phase 3'
            });
var format_support_phase1_16 = new ol.format.GeoJSON();
var features_support_phase1_16 = format_support_phase1_16.readFeatures(json_support_phase1_16, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_support_phase1_16 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_support_phase1_16.addFeatures(features_support_phase1_16);
var lyr_support_phase1_16 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_support_phase1_16, 
                style: style_support_phase1_16,
                popuplayertitle: 'support_phase 1',
                interactive: true,
                title: '<img src="styles/legend/support_phase1_16.png" /> support_phase 1'
            });
var format_WASHenteredwithinVEMIS_17 = new ol.format.GeoJSON();
var features_WASHenteredwithinVEMIS_17 = format_WASHenteredwithinVEMIS_17.readFeatures(json_WASHenteredwithinVEMIS_17, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHenteredwithinVEMIS_17 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHenteredwithinVEMIS_17.addFeatures(features_WASHenteredwithinVEMIS_17);
var lyr_WASHenteredwithinVEMIS_17 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHenteredwithinVEMIS_17, 
                style: style_WASHenteredwithinVEMIS_17,
                popuplayertitle: 'WASH entered within VEMIS',
                interactive: true,
    title: 'WASH entered within VEMIS<br />\
    <img src="styles/legend/WASHenteredwithinVEMIS_17_0.png" /> n<br />\
    <img src="styles/legend/WASHenteredwithinVEMIS_17_1.png" /> y<br />' });
var format_Trainingdone_18 = new ol.format.GeoJSON();
var features_Trainingdone_18 = format_Trainingdone_18.readFeatures(json_Trainingdone_18, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Trainingdone_18 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Trainingdone_18.addFeatures(features_Trainingdone_18);
var lyr_Trainingdone_18 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Trainingdone_18, 
                style: style_Trainingdone_18,
                popuplayertitle: 'Training done',
                interactive: true,
    title: 'Training done<br />\
    <img src="styles/legend/Trainingdone_18_0.png" /> n<br />\
    <img src="styles/legend/Trainingdone_18_1.png" /> y<br />' });
var format_BaselineAssessment_19 = new ol.format.GeoJSON();
var features_BaselineAssessment_19 = format_BaselineAssessment_19.readFeatures(json_BaselineAssessment_19, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_BaselineAssessment_19 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_BaselineAssessment_19.addFeatures(features_BaselineAssessment_19);
var lyr_BaselineAssessment_19 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_BaselineAssessment_19, 
                style: style_BaselineAssessment_19,
                popuplayertitle: 'Baseline Assessment',
                interactive: true,
    title: 'Baseline Assessment<br />\
    <img src="styles/legend/BaselineAssessment_19_0.png" /> n<br />\
    <img src="styles/legend/BaselineAssessment_19_1.png" /> y<br />' });
var format_2025SANMAProcurementneedsassessment_20 = new ol.format.GeoJSON();
var features_2025SANMAProcurementneedsassessment_20 = format_2025SANMAProcurementneedsassessment_20.readFeatures(json_2025SANMAProcurementneedsassessment_20, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_2025SANMAProcurementneedsassessment_20 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_2025SANMAProcurementneedsassessment_20.addFeatures(features_2025SANMAProcurementneedsassessment_20);
var lyr_2025SANMAProcurementneedsassessment_20 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_2025SANMAProcurementneedsassessment_20, 
                style: style_2025SANMAProcurementneedsassessment_20,
                popuplayertitle: '2025 SANMA Procurement needs assessment',
                interactive: true,
    title: '2025 SANMA Procurement needs assessment<br />\
    <img src="styles/legend/2025SANMAProcurementneedsassessment_20_0.png" /> PS<br />\
    <img src="styles/legend/2025SANMAProcurementneedsassessment_20_1.png" /> SS<br />' });
var group_SupportPhase = new ol.layer.Group({
                                layers: [lyr_support_phase3_15,lyr_support_phase1_16,],
                                fold: 'open',
                                title: 'Support Phase'});
var group_DeliveryPointorMethod = new ol.layer.Group({
                                layers: [lyr_DeliveryShipWSanto_6,lyr_DeliveryShiptoTasarikiLandTransport_7,lyr_delivery__ship_to_tasarikiland_transport_8,lyr_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9,lyr_DeliveryByBoat_10,lyr_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11,lyr_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12,lyr_DeliveryShipBBcoast_13,lyr_DeliveryLandTransport_14,],
                                fold: 'open',
                                title: 'Delivery Point or Method'});

lyr_GoogleSatellite_0.setVisible(true);lyr_GHWS_1.setVisible(false);lyr_vip_inclusive_2.setVisible(false);lyr_Doubleoffsettwinpittoilet_3.setVisible(false);lyr_rwc_12m_no_tank_4.setVisible(false);lyr_rwc_12m_w_6kl_tank_5.setVisible(false);lyr_DeliveryShipWSanto_6.setVisible(false);lyr_DeliveryShiptoTasarikiLandTransport_7.setVisible(false);lyr_delivery__ship_to_tasarikiland_transport_8.setVisible(false);lyr_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.setVisible(false);lyr_DeliveryByBoat_10.setVisible(false);lyr_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.setVisible(false);lyr_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.setVisible(false);lyr_DeliveryShipBBcoast_13.setVisible(false);lyr_DeliveryLandTransport_14.setVisible(false);lyr_support_phase3_15.setVisible(false);lyr_support_phase1_16.setVisible(false);lyr_WASHenteredwithinVEMIS_17.setVisible(false);lyr_Trainingdone_18.setVisible(false);lyr_BaselineAssessment_19.setVisible(false);lyr_2025SANMAProcurementneedsassessment_20.setVisible(true);
var layersList = [lyr_GoogleSatellite_0,lyr_GHWS_1,lyr_vip_inclusive_2,lyr_Doubleoffsettwinpittoilet_3,lyr_rwc_12m_no_tank_4,lyr_rwc_12m_w_6kl_tank_5,group_DeliveryPointorMethod,group_SupportPhase,lyr_WASHenteredwithinVEMIS_17,lyr_Trainingdone_18,lyr_BaselineAssessment_19,lyr_2025SANMAProcurementneedsassessment_20];
lyr_GHWS_1.set('fieldAliases', {'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_vip_inclusive_2.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_Doubleoffsettwinpittoilet_3.set('fieldAliases', {'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_rwc_12m_no_tank_4.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_rwc_12m_w_6kl_tank_5.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryShipWSanto_6.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryShiptoTasarikiLandTransport_7.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_delivery__ship_to_tasarikiland_transport_8.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryByBoat_10.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryShipBBcoast_13.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_DeliveryLandTransport_14.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_support_phase3_15.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_support_phase1_16.set('fieldAliases', {'fid': 'fid', 'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_WASHenteredwithinVEMIS_17.set('fieldAliases', {'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_Trainingdone_18.set('fieldAliases', {'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_BaselineAssessment_19.set('fieldAliases', {'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_2025SANMAProcurementneedsassessment_20.set('fieldAliases', {'Reg No': 'Reg No', 'School Name': 'School Name', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Province': 'Province', 'Island': 'Island', 'Language': 'Language', 'Type': 'Type', 'Baseline': 'Baseline', 'Traing done': 'Traing done', 'WASH enterred into VEMIS': 'WASH enterred into VEMIS', 'WIP done': 'WIP done', 'Delivery Port': 'Delivery Port', '6k l tank': '6k l tank', 'RWC 12m w 6kL tank': 'RWC 12m w 6kL tank', 'RWC 8m w 1kL tank': 'RWC 8m w 1kL tank', 'RWC 12m no tank': 'RWC 12m no tank', 'RWC 8m no tank': 'RWC 8m no tank', 'Tapstand': 'Tapstand', 'Double offset twin pit toilet': 'Double offset twin pit toilet', 'Shower (bucket)': 'Shower (bucket)', 'Shower (piped)': 'Shower (piped)', 'VIP inclusive': 'VIP inclusive', 'GHWS': 'GHWS', 'Roofing Iron': 'Roofing Iron', 'Toolkit - full': 'Toolkit - full', 'sanitation block': 'sanitation block', 'Other materials': 'Other materials', 'Delivery  Contact #1': 'Delivery  Contact #1', 'Delivery Contact #2': 'Delivery Contact #2', 'Delivery  Contact #3': 'Delivery  Contact #3', 'Comments': 'Comments', 'support phase': 'support phase', 'Visit': 'Visit', 'Location': 'Location', 'Delivery point or method': 'Delivery point or method', });
lyr_GHWS_1.set('fieldImages', {'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': '', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': '', });
lyr_vip_inclusive_2.set('fieldImages', {'fid': 'TextEdit', 'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': 'TextEdit', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': 'TextEdit', });
lyr_Doubleoffsettwinpittoilet_3.set('fieldImages', {'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': '', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': '', });
lyr_rwc_12m_no_tank_4.set('fieldImages', {'fid': 'TextEdit', 'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': 'TextEdit', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': 'TextEdit', });
lyr_rwc_12m_w_6kl_tank_5.set('fieldImages', {'fid': 'TextEdit', 'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': 'TextEdit', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': 'TextEdit', });
lyr_DeliveryShipWSanto_6.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryShiptoTasarikiLandTransport_7.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_delivery__ship_to_tasarikiland_transport_8.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryByBoat_10.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryShipBBcoast_13.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_DeliveryLandTransport_14.set('fieldImages', {'fid': '', 'Reg No': '', 'School Name': '', 'Latitude': '', 'Longitude': '', 'Province': '', 'Island': '', 'Language': '', 'Type': '', 'Baseline': '', 'Traing done': '', 'WASH enterred into VEMIS': '', 'WIP done': '', 'Delivery Port': '', '6k l tank': '', 'RWC 12m w 6kL tank': '', 'RWC 8m w 1kL tank': '', 'RWC 12m no tank': '', 'RWC 8m no tank': '', 'Tapstand': '', 'Double offset twin pit toilet': '', 'Shower (bucket)': '', 'Shower (piped)': '', 'VIP inclusive': '', 'GHWS': '', 'Roofing Iron': '', 'Toolkit - full': '', 'sanitation block': '', 'Other materials': '', 'Delivery  Contact #1': '', 'Delivery Contact #2': '', 'Delivery  Contact #3': '', 'Comments': '', 'support phase': '', 'Visit': '', 'Location': '', 'Delivery point or method': '', });
lyr_support_phase3_15.set('fieldImages', {'fid': 'TextEdit', 'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': 'TextEdit', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': 'TextEdit', });
lyr_support_phase1_16.set('fieldImages', {'fid': 'TextEdit', 'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': 'TextEdit', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': 'TextEdit', });
lyr_WASHenteredwithinVEMIS_17.set('fieldImages', {'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': '', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': '', });
lyr_Trainingdone_18.set('fieldImages', {'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': '', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': '', });
lyr_BaselineAssessment_19.set('fieldImages', {'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': '', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': '', });
lyr_2025SANMAProcurementneedsassessment_20.set('fieldImages', {'Reg No': 'Range', 'School Name': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'CheckBox', 'Province': 'TextEdit', 'Island': 'TextEdit', 'Language': 'TextEdit', 'Type': 'TextEdit', 'Baseline': 'TextEdit', 'Traing done': 'TextEdit', 'WASH enterred into VEMIS': 'TextEdit', 'WIP done': 'TextEdit', 'Delivery Port': 'TextEdit', '6k l tank': 'TextEdit', 'RWC 12m w 6kL tank': 'Range', 'RWC 8m w 1kL tank': 'CheckBox', 'RWC 12m no tank': 'Range', 'RWC 8m no tank': 'CheckBox', 'Tapstand': 'CheckBox', 'Double offset twin pit toilet': 'Range', 'Shower (bucket)': 'Range', 'Shower (piped)': 'Range', 'VIP inclusive': 'Range', 'GHWS': 'Range', 'Roofing Iron': 'CheckBox', 'Toolkit - full': 'CheckBox', 'sanitation block': 'Range', 'Other materials': 'TextEdit', 'Delivery  Contact #1': 'TextEdit', 'Delivery Contact #2': 'TextEdit', 'Delivery  Contact #3': 'TextEdit', 'Comments': 'TextEdit', 'support phase': '', 'Visit': 'TextEdit', 'Location': 'TextEdit', 'Delivery point or method': '', });
lyr_GHWS_1.set('fieldLabels', {'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_vip_inclusive_2.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_Doubleoffsettwinpittoilet_3.set('fieldLabels', {'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_rwc_12m_no_tank_4.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'header label - visible with data', });
lyr_rwc_12m_w_6kl_tank_5.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryShipWSanto_6.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryShiptoTasarikiLandTransport_7.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_delivery__ship_to_tasarikiland_transport_8.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryShiptoArakiorLandTransporttoLandingsiteandthenbyBoat_9.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryByBoat_10.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'hidden field', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryLandTransporttoLandingsitethenbyBoattoschool_11.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryShiptoMaloNanukuthenLandTransporttoIndividualSchools_12.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryShipBBcoast_13.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_DeliveryLandTransport_14.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_support_phase3_15.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'hidden field', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_support_phase1_16.set('fieldLabels', {'fid': 'hidden field', 'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'header label - visible with data', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_WASHenteredwithinVEMIS_17.set('fieldLabels', {'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_Trainingdone_18.set('fieldLabels', {'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_BaselineAssessment_19.set('fieldLabels', {'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'hidden field', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'hidden field', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'hidden field', 'GHWS': 'hidden field', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'hidden field', });
lyr_2025SANMAProcurementneedsassessment_20.set('fieldLabels', {'Reg No': 'hidden field', 'School Name': 'header label - visible with data', 'Latitude': 'header label - visible with data', 'Longitude': 'header label - visible with data', 'Province': 'hidden field', 'Island': 'hidden field', 'Language': 'hidden field', 'Type': 'hidden field', 'Baseline': 'hidden field', 'Traing done': 'hidden field', 'WASH enterred into VEMIS': 'hidden field', 'WIP done': 'hidden field', 'Delivery Port': 'hidden field', '6k l tank': 'hidden field', 'RWC 12m w 6kL tank': 'header label - visible with data', 'RWC 8m w 1kL tank': 'hidden field', 'RWC 12m no tank': 'hidden field', 'RWC 8m no tank': 'hidden field', 'Tapstand': 'hidden field', 'Double offset twin pit toilet': 'header label - visible with data', 'Shower (bucket)': 'hidden field', 'Shower (piped)': 'hidden field', 'VIP inclusive': 'header label - visible with data', 'GHWS': 'header label - visible with data', 'Roofing Iron': 'hidden field', 'Toolkit - full': 'hidden field', 'sanitation block': 'hidden field', 'Other materials': 'hidden field', 'Delivery  Contact #1': 'hidden field', 'Delivery Contact #2': 'hidden field', 'Delivery  Contact #3': 'hidden field', 'Comments': 'hidden field', 'support phase': 'hidden field', 'Visit': 'hidden field', 'Location': 'hidden field', 'Delivery point or method': 'header label - visible with data', });
lyr_2025SANMAProcurementneedsassessment_20.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});