var json_rwc_12m_no_tank_4 = {
"type": "FeatureCollection",
"name": "rwc_12m_no_tank_4",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": "9", "Reg No": 22264.0, "School Name": "Saletui", "Latitude": -15.64602, "Longitude": null, "Province": "Sanma", "Island": "South Santo", "Language": "ENG", "Type": "PS", "Baseline": "y", "Traing done": "y", "WASH enterred into VEMIS": "y", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": 1.0, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 2.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 166.8328639, -15.6460161 ] } },
{ "type": "Feature", "properties": { "fid": "24", "Reg No": 22286.0, "School Name": "Paireve (Nasulesule)", "Latitude": -15.5897, "Longitude": null, "Province": "Sanma", "Island": "South Santo", "Language": "ENG", "Type": "PS", "Baseline": "y", "Traing done": "y", "WASH enterred into VEMIS": "n", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": null, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 2.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 166.9036069, -15.5897008 ] } },
{ "type": "Feature", "properties": { "fid": "25", "Reg No": 22248.0, "School Name": "St. Pierre (Okoro)", "Latitude": -15.58502, "Longitude": null, "Province": "Sanma", "Island": "South Santo", "Language": "FRE", "Type": "PS", "Baseline": "y", "Traing done": "n", "WASH enterred into VEMIS": "n", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": 1.0, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 1.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 166.92095470000001, -15.5850208 ] } },
{ "type": "Feature", "properties": { "fid": "29", "Reg No": 21912.0, "School Name": "Dombulu", "Latitude": -15.56862, "Longitude": null, "Province": "Sanma", "Island": "Tutuba", "Language": "ENG", "Type": "PS", "Baseline": "y", "Traing done": "n", "WASH enterred into VEMIS": "n", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": null, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 2.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 167.2729316, -15.5686191 ] } },
{ "type": "Feature", "properties": { "fid": "38", "Reg No": 222326.0, "School Name": "Tavumae", "Latitude": -15.53035, "Longitude": null, "Province": "Sanma", "Island": "South Santo", "Language": "ENG", "Type": "PS", "Baseline": "y", "Traing done": "y", "WASH enterred into VEMIS": "n", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": 1.0, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 1.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 166.9856148, -15.5303522 ] } },
{ "type": "Feature", "properties": { "fid": "73", "Reg No": 22204.0, "School Name": "Balon Primary", "Latitude": -15.36039, "Longitude": null, "Province": "Sanma", "Island": "Fanafo Santo", "Language": "ENG", "Type": "PS", "Baseline": "y", "Traing done": "y", "WASH enterred into VEMIS": "y", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": null, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 2.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 4.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 167.136265, -15.360386 ] } },
{ "type": "Feature", "properties": { "fid": "91", "Reg No": 22278.0, "School Name": "Winsao", "Latitude": -15.2374, "Longitude": null, "Province": "Sanma", "Island": "BB Inland Santo", "Language": "ENG", "Type": "PS", "Baseline": "n", "Traing done": "y", "WASH enterred into VEMIS": "n", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": null, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 1.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 166.8380524, -15.2374035 ] } },
{ "type": "Feature", "properties": { "fid": "109", "Reg No": 22247.0, "School Name": "John Noble Mackenzie", "Latitude": -14.93141, "Longitude": null, "Province": "Sanma", "Island": "WC Santo", "Language": "ENG", "Type": "PS", "Baseline": "y", "Traing done": "y", "WASH enterred into VEMIS": "n", "WIP done": null, "Delivery Port": null, "6k l tank": null, "RWC 12m w 6kL tank": 1.0, "RWC 8m w 1kL tank": null, "RWC 12m no tank": 1.0, "RWC 8m no tank": null, "Tapstand": null, "Double offset twin pit toilet": null, "Shower (bucket)": null, "Shower (piped)": null, "VIP inclusive": 2.0, "GHWS": null, "Roofing Iron": null, "Toolkit - full": null, "sanitation block": null, "Other materials": null, "Delivery  Contact ": null }, "geometry": { "type": "Point", "coordinates": [ 166.575347, -14.931408 ] } }
]
}
